apiVersion: v1
kind: ConfigMap
metadata:
    name: commands-service-config
data:
    NODE_ENV: "production"
    PORT: "8080"
    PGHOST: "commands-postgres"
    PGPORT: "5432"
    PGDATABASE: "commands_db"
    RABBITMQ_HOST: "rabbitmq:5672"
    CATALOG_SERVICE_URL: "http://catalog-service:8080/catalog"
