apiVersion: apps/v1
kind: Deployment
metadata:
    name: commands-service
    labels:
        app: commands-service
spec:
    replicas: 1
    selector:
        matchLabels:
            app: commands-service
    template:
        metadata:
            labels:
                app: commands-service
        spec:
            imagePullSecrets:
                - name: scw-registry-secret
            containers:
                - name: commands-service
                  image: rg.fr-par.scw.cloud/good-food-container-registry/commands-service:87b2740da84fc0ea393bbd13a374e0805baa5296
                  imagePullPolicy: Always
                  ports:
                      - containerPort: 8080
                  resources:
                      requests:
                          memory: "32Mi"
                          cpu: "10m"
                      limits:
                          memory: "64Mi"
                          cpu: "100m"
                  envFrom:
                      - configMapRef:
                            name: commands-service-config
                      - secretRef:
                            name: commands-service-db-secret
                      - secretRef:
                            name: good-food-jwt-secret
                      - secretRef:
                            name: rabbitmq-secret
---
apiVersion: v1
kind: Service
metadata:
    name: commands-service
spec:
    selector:
        app: commands-service
    ports:
        - protocol: TCP
          port: 8080
          targetPort: 8080
